/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GameBoard: typeof import('./components/GameBoard.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
  }
}
